Update validate_pr_description.yml

diff --git a/.github/workflows/validate_pr_description.yml b/.github/workflows/validate_pr_description.yml
--- a/.github/workflows/validate_pr_description.yml
+++ b/.github/workflows/validate_pr_description.yml
@@ -23,12 +23,14 @@ jobs:
         uses: ./.github/actions/validate_pr_description
         with:
           pr_body: "${{ github.event.pull_request.body }}"
+        continue-on-error: true
 
       - name: Test output
         if: always()
-        run: echo "Result of validation is  ${{ steps.validate.outputs.status }}"
-        
+        run: echo "Result of validation is  ${{ steps.validate.outputs.status }}"    
 
       - name: Set status
         if: failure()
-        run: echo "Validation failed."
+        run: |
+          echo "Validation failed."
+          exit 78  # Нейтральный статус
